version: '3.9'

services:
  crm-api:
    container_name: crm-api
    build: .
    ports:
      - 1677:1677
    networks:
      - CRMNet


networks:
  CRMNet:
    name: CRMNet
    driver: bridge
    external: true

volumes:
  db: